### ISSUE TITLE
How to properly run on DB21M

### ISSUE THREAD

**Issue by SPGC** [duckietown/dt-ros2-interface#1]
Hi!
I've pulled image of your repository from Dockerhub on my Duckiebot and tried to run it with comand:
`docker run -i duckietown/dt-ros2-interface:ente-arm64v8 /launch/dt-ros2-interface/sensor-camera.sh`
But instead working node I receive this message:
```
==> Entrypoint
   INFO: The environment variable VEHICLE_NAME is not set. Using '4dc98836eb0e'.
   INFO: Network configured successfully.
WARNING: robot_type file does not exist. Using 'duckiebot' as default type.
WARNING: robot_configuration file does not exist.
WARNING: robot_hardware file does not exist.
WARNING: colcon setup file not found: /opt/colcon/install/setup.bash
<== Entrypoint
==> Launching app...
OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 4: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 4: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 4: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
Traceback (most recent call last):
  File "/code/install/camera_driver/lib/camera_driver/camera_driver_node", line 33, in <module>
    sys.exit(load_entry_point('camera-driver', 'console_scripts', 'camera_driver_node')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/install/camera_driver/lib/camera_driver/camera_driver_node", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/code/build/camera_driver/camera_driver/camera_driver_node.py", line 6, in <module>
    from sensor_msgs.msg import CompressedImage as ROS2CompressedImage, CameraInfo as ROS2CameraInfo
  File "/opt/ros/rolling/lib/python3.12/site-packages/sensor_msgs/msg/__init__.py", line 2, in <module>
    from sensor_msgs.msg._camera_info import CameraInfo  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ros/rolling/lib/python3.12/site-packages/sensor_msgs/msg/_camera_info.py", line 25, in <module>
    import numpy  # noqa: E402, I100
    ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/numpy/__init__.py", line 130, in <module>
    from numpy.__config__ import show as show_config
  File "/usr/local/lib/python3.12/dist-packages/numpy/__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "/usr/local/lib/python3.12/dist-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/usr/local/lib/python3.12/dist-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/usr/local/lib/python3.12/dist-packages/numpy/core/overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
  File "<frozen importlib._bootstrap>", line 463, in _lock_unlock_module
KeyboardInterrupt
[ros2run]: Interrupt
<== App terminated!
```
So the question is: is it possible to run your repository on DB21M and if so, how to properly do it?

**Comment by Tuxliri** [comment]
Hi @SPGC, this repo was still experimental at the time. You can try using it now.
